### ISSUE TITLE
error on cookiecutter

### ISSUE THREAD

**Issue by bendichter** [nwb-extensions/ndx-template#23]
```bash
$ cookiecutter gh:nwb-extensions/ndx-template
You've downloaded /Users/bendichter/.cookiecutters/ndx-template before. Is it okay to delete and re-download it? [yes]: 
namespace [ndx-my-namespace]: ndx-experimenters
description [An NWB:N extension]: allows you to list more than one experimenter per session
author [My Name]: Ben Dichter
email [my_email@example.com]: ben.dichter@gmail.com
github_username [myname]: bendichter
copyright [2019, Ben Dichter]: 
version [0.1.0]: 
release [alpha]: 
license [BSD 3-Clause]: 
py_pkg_name [ndx_experimenters]: 
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/conf.py.
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/index.rst.
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.

Cleaning file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/conf.py
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/_static/theme_overrides.css
Updating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/conf.py
Updating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/conf_doc_autogen.py
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/Makefile
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/description.rst
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/release_notes.rst
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/credits.rst
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/format.rst
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/source/index.rst
Creating file /Users/bendichter/dev/pynwb/ndx-experimenters/docs/README.md
Traceback (most recent call last):
  File "src/spec/create_extension_spec.py", line 44, in <module>
    main()
  File "src/spec/create_extension_spec.py", line 40, in main
    export_spec(ns_builder, new_data_types)
  File "/Users/bendichter/dev/pynwb/ndx-experimenters/src/spec/export_spec.py", line 20, in export_spec
    if ns_builder.name is None:
AttributeError: 'NWBNamespaceBuilder' object has no attribute 'name'
Traceback (most recent call last):
  File "/var/folders/mn/b_p5fwjx3999zx0qdqhvqjvw0000gn/T/tmp7i7d3a5t.py", line 55, in <module>
    main()
  File "/var/folders/mn/b_p5fwjx3999zx0qdqhvqjvw0000gn/T/tmp7i7d3a5t.py", line 43, in main
    _create_extension_spec()
  File "/var/folders/mn/b_p5fwjx3999zx0qdqhvqjvw0000gn/T/tmp7i7d3a5t.py", line 28, in _create_extension_spec
    check_call([sys.executable, spec_dir + "/create_extension_spec.py"])
  File "/Users/bendichter/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/bendichter/anaconda3/bin/python', 'src/spec/create_extension_spec.py']' returned non-zero exit status 1.
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by rly** [comment]
This will be fixed in the next pynwb release which will use the latest hdmf release, where `name` is an attribute on `NamespaceBuilder`.

**Comment by rly** [comment]
This is fixed now.
